namespace GBA.Common.ResourceNames;

public static class SharedResourceNames {
    public const string INVALID_CREDENTIALS = "InvalidCredentials";

    public const string INVALID_USERNAME = "InvalidUserName";

    public const string INVALID_EMAIL = "InvalidEmail";

    public const string INVALID_PASSWORD = "InvalidPassword";

    public const string USER_DISABLED = "UserDisabled";

    public const string SYNC_STARTED = "SyncStarted";

    public const string SYNC_FINISHED = "SyncFinished";

    public const string EXCHANGE_RATE_HISTORY_SYNC_START = "EXCHANGE_RATE_HISTORY_SYNC_START";

    public const string EXCHANGE_RATE_HISTORY_SYNC_END = "EXCHANGE_RATE_HISTORY_SYNC_END";

    public const string ACCOUNTING_SYNC_START = "ACCOUNTING_SYNC_START";

    public const string ACCOUNTING_SYNC_END = "ACCOUNTING_SYNC_END";

    public const string REGIONS_SYNC_START = "REGIONS_SYNC_START";

    public const string REGIONS_SYNC_END = "REGIONS_SYNC_END";

    public const string CLIENTS_AND_SUPPLIERS_SYNC_START = "CLIENTS_AND_SUPPLIERS_SYNC_START";

    public const string CLIENTS_AND_SUPPLIERS_SYNC_END = "CLIENTS_AND_SUPPLIERS_SYNC_END";

    public const string TAX_INSPECTIONS_SYNC_START = "TAX_INSPECTIONS_SYNC_START";

    public const string TAX_INSPECTIONS_SYNC_END = "TAX_INSPECTIONS_SYNC_END";

    public const string ORGANIZATIONS_SYNC_START = "ORGANIZATIONS_SYNC_START";

    public const string ORGANIZATIONS_SYNC_END = "ORGANIZATIONS_SYNC_END";

    public const string STORAGES_SYNC_START = "STORAGES_SYNC_START";

    public const string STORAGES_SYNC_END = "STORAGES_SYNC_END";

    public const string PRICINGS_SYNC_START = "PRICINGS_SYNC_START";

    public const string PRICINGS_SYNC_END = "PRICINGS_SYNC_END";

    public const string AGREEMENTS_AND_DISCOUNTS_SYNC_START = "AGREEMENTS_AND_DISCOUNTS_SYNC_START";

    public const string AGREEMENTS_AND_DISCOUNTS_SYNC_END = "AGREEMENTS_AND_DISCOUNTS_SYNC_END";

    public const string DELIVERY_RECIPIENTS_SYNC_START = "DELIVERY_RECIPIENTS_SYNC_START";

    public const string DELIVERY_RECIPIENTS_SYNC_END = "DELIVERY_RECIPIENTS_SYNC_END";

    public const string CONSIGNMENTS_SYNC_START = "CONSIGNMENTS_SYNC_START";

    public const string CONSIGNMENTS_SYNC_END = "CONSIGNMENTS_SYNC_END";

    public const string CONSIGNMENTS_SYNC_EXCEPTION_LIST = "CONSIGNMENTS_SYNC_EXCEPTION_LIST";

    public const string ORDERS_SYNC_EXCEPTION_LIST = "ORDERS_SYNC_EXCEPTION_LIST";

    public const string CASH_REGISTERS_SYNC_START = "CASH_REGISTERS_SYNC_START";

    public const string CASH_REGISTERS_SYNC_END = "CASH_REGISTERS_SYNC_END";

    public const string BANK_REGISTERS_SYNC_START = "BANK_REGISTERS_SYNC_START";

    public const string BANK_REGISTERS_SYNC_END = "BANK_REGISTERS_SYNC_END";

    public const string BANKS_SYNC_START = "BANKS_SYNC_START";

    public const string BANKS_SYNC_END = "BANKS_SYNC_END";

    public const string MEASURE_UNITS_SYNC_START = "MEASURE_UNITS_SYNC_START";

    public const string MEASURE_UNITS_SYNC_END = "MEASURE_UNITS_SYNC_END";

    public const string PRODUCT_GROUPS_SYNC_START = "PRODUCT_GROUPS_SYNC_START";

    public const string PRODUCT_GROUPS_SYNC_END = "PRODUCT_GROUPS_SYNC_END";

    public const string PRODUCTS_SYNC_START = "PRODUCTS_SYNC_START";

    public const string PRODUCTS_SYNC_END = "PRODUCTS_SYNC_END";

    public const string ASSIGN_PRODUCTS_TO_PRODUCT_GROUPS_START = "ASSIGN_PRODUCTS_TO_PRODUCT_GROUPS_START";

    public const string ASSIGN_PRODUCTS_TO_PRODUCT_GROUPS_END = "ASSIGN_PRODUCTS_TO_PRODUCT_GROUPS_END";

    public const string ASSIGN_ANALOGUES_START = "ASSIGN_ANALOGUES_START";

    public const string ASSIGN_ANALOGUES_END = "ASSIGN_ANALOGUES_END";

    public const string ASSIGN_COMPONENTS_START = "ASSIGN_COMPONENTS_START";

    public const string ASSIGN_COMPONENTS_END = "ASSIGN_COMPONENTS_END";

    public const string ORIGINAL_NUMBERS_SYNC_START = "ORIGINAL_NUMBERS_SYNC_START";

    public const string ORIGINAL_NUMBERS_SYNC_END = "ORIGINAL_NUMBERS_SYNC_END";

    public const string PRODUCT_PRICES_SYNC_START = "PRODUCT_PRICES_SYNC_START";

    public const string PRODUCT_PRICES_SYNC_END = "PRODUCT_PRICES_SYNC_END";

    public const string REORGANIZING_CLIENT_STRUCTURE_START = "REORGANIZING_CLIENT_STRUCTURE_START";

    public const string REORGANIZING_CLIENT_STRUCTURE_END = "REORGANIZING_CLIENT_STRUCTURE_END";

    public const string OUTCOME_DOCUMENTS_SYNC_START = "OUTCOME_DOCUMENTS_SYNC_START";

    public const string OUTCOME_DOCUMENTS_SYNC_END = "OUTCOME_DOCUMENTS_SYNC_END";

    public const string SYNC_ERROR = "SYNC_ERROR";

    public const string DAILY_SYNC_START = "DAILY_SYNC_START";

    public const string DAILY_SYNC_END = "DAILY_SYNC_END";

    public const string PRODUCT_INCOME_SYNC_START = "PRODUCT_INCOME_SYNC_START";

    public const string PRODUCT_INCOME_SYNC_END = "PRODUCT_INCOME_SYNC_END";

    public const string PRODUCT_CAPITALIZATION_SYNC_START = "PRODUCT_CAPITALIZATION_SYNC_START";

    public const string PRODUCT_CAPITALIZATION_SYNC_END = "PRODUCT_CAPITALIZATION_SYNC_END";

    public const string CLIENT_RETURN_SYNC_START = "CLIENT_RETURN_SYNC_START";

    public const string CLIENT_RETURN_SYNC_END = "CLIENT_RETURN_SYNC_END";

    public const string PRODUCT_TRANSFER_SYNC_START = "PRODUCT_TRANSFER_SYNC_START";

    public const string PRODUCT_TRANSFER_SYNC_END = "PRODUCT_TRANSFER_SYNC_END";

    public const string PRODUCT_DEPRECIATION_SYNC_START = "PRODUCT_DEPRECIATION_SYNC_START";

    public const string PRODUCT_DEPRECIATION_SYNC_END = "PRODUCT_DEPRECIATION_SYNC_END";

    public const string ACT_PRODUCT_TRANSFER_SYNC_START = "ACT_PRODUCT_TRANSFER_SYNC_START";

    public const string ACT_PRODUCT_TRANSFER_SYNC_END = "ACT_PRODUCT_TRANSFER_SYNC_END";

    public const string SALES_SYNC_START = "SALES_SYNC_START";

    public const string SALES_SYNC_END = "SALES_SYNC_END";

    public const string INCOME_ORDERS_CASH_SYNC_START = "INCOME_ORDERS_CASH_SYNC_START";

    public const string INCOME_ORDERS_CASH_SYNC_END = "INCOME_ORDERS_CASH_SYNC_END";

    public const string INCOME_ORDERS_BANK_SYNC_START = "INCOME_ORDERS_BANK_SYNC_START";

    public const string INCOME_ORDERS_BANK_SYNC_END = "INCOME_ORDERS_BANK_SYNC_END";

    public const string OUTCOME_ORDERS_CASH_SYNC_START = "OUTCOME_ORDERS_CASH_SYNC_START";

    public const string OUTCOME_ORDERS_CASH_SYNC_END = "OUTCOME_ORDERS_CASH_SYNC_END";

    public const string INTERNAL_MOVEMENT_OF_FUNDS_START = "INTERNAL_MOVEMENT_OF_FUNDS_START";

    public const string INTERNAL_MOVEMENT_OF_FUNDS_END = "INTERNAL_MOVEMENT_OF_FUNDS_END";

    public const string OUTCOME_ORDERS_BANK_SYNC_START = "OUTCOME_ORDERS_BANK_SYNC_START";

    public const string OUTCOME_ORDERS_BANK_SYNC_END = "OUTCOME_ORDERS_BANK_SYNC_END";
}