// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using GBA.Data;

#nullable disable

namespace GBA.Data.Migrations.ConcordDataAnalytic
{
    [DbContext(typeof(ConcordDataAnalyticContext))]
    [Migration("20250106113951_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("GBA.Domain.Entities.Sales.ProductAvailabilityDataHistory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<double>("Amount")
                        .HasColumnType("float")
                        .HasColumnName("Amount");

                    b.Property<DateTime>("Created")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<bool>("Deleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("0");

                    b.Property<Guid>("NetUid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("NetUID")
                        .HasDefaultValueSql("newid()");

                    b.Property<long>("StockStateStorageID")
                        .HasColumnType("bigint");

                    b.Property<long?>("StorageId")
                        .HasColumnType("bigint")
                        .HasColumnName("StorageId");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("StockStateStorageID");

                    b.ToTable("ProductAvailabilityDataHistory", (string)null);
                });

            modelBuilder.Entity("GBA.Domain.Entities.Sales.ProductPlacementDataHistory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("CellNumber")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<long?>("ConsignmentItemId")
                        .HasColumnType("bigint")
                        .HasColumnName("ConsignmentItemId");

                    b.Property<string>("ConsignmentNumber")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ConsignmentNumber");

                    b.Property<DateTime>("Created")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<bool>("Deleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("0");

                    b.Property<string>("MainOriginalNumber")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("MainOriginalNumber");

                    b.Property<string>("NameUA")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("NameUA");

                    b.Property<Guid>("NetUid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("NetUID")
                        .HasDefaultValueSql("newid()");

                    b.Property<long?>("ProductAvailabilityDataHistoryID")
                        .HasColumnType("bigint");

                    b.Property<long?>("ProductId")
                        .HasColumnType("bigint")
                        .HasColumnName("ProductId");

                    b.Property<double>("Qty")
                        .HasColumnType("float");

                    b.Property<string>("RowNumber")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<long?>("StorageId")
                        .HasColumnType("bigint")
                        .HasColumnName("StorageId");

                    b.Property<string>("StorageNumber")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("datetime2");

                    b.Property<string>("VendorCode")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("VendorCode");

                    b.HasKey("Id");

                    b.HasIndex("ProductAvailabilityDataHistoryID");

                    b.ToTable("ProductPlacementDataHistory", (string)null);
                });

            modelBuilder.Entity("GBA.Domain.Entities.Sales.StockStateStorage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<int>("ChangeTypeOrderItem")
                        .HasColumnType("int")
                        .HasColumnName("ChangeTypeOrderItem");

                    b.Property<DateTime>("Created")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<bool>("Deleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("0");

                    b.Property<Guid>("NetUid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("NetUID")
                        .HasDefaultValueSql("newid()");

                    b.Property<long?>("ProductId")
                        .HasColumnType("bigint")
                        .HasColumnName("ProductId");

                    b.Property<double>("QtyHistory")
                        .HasColumnType("float")
                        .HasColumnName("QtyHistory");

                    b.Property<long?>("SaleId")
                        .HasColumnType("bigint")
                        .HasColumnName("SaleId");

                    b.Property<long?>("SaleNumberId")
                        .HasColumnType("bigint")
                        .HasColumnName("SaleNumberId");

                    b.Property<double>("TotalCartReservedUK")
                        .HasColumnType("float")
                        .HasColumnName("TotalCartReservedUK");

                    b.Property<double>("TotalReservedUK")
                        .HasColumnType("float")
                        .HasColumnName("TotalReservedUK");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("datetime2");

                    b.Property<long?>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("UserID");

                    b.HasKey("Id");

                    b.ToTable("StockStateStorage", (string)null);
                });

            modelBuilder.Entity("GBA.Domain.Entities.Sales.ProductAvailabilityDataHistory", b =>
                {
                    b.HasOne("GBA.Domain.Entities.Sales.StockStateStorage", "StockStateStorage")
                        .WithMany("ProductAvailabilityDataHistory")
                        .HasForeignKey("StockStateStorageID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StockStateStorage");
                });

            modelBuilder.Entity("GBA.Domain.Entities.Sales.ProductPlacementDataHistory", b =>
                {
                    b.HasOne("GBA.Domain.Entities.Sales.ProductAvailabilityDataHistory", "ProductAvailabilityDataHistory")
                        .WithMany("ProductPlacementDataHistory")
                        .HasForeignKey("ProductAvailabilityDataHistoryID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("ProductAvailabilityDataHistory");
                });

            modelBuilder.Entity("GBA.Domain.Entities.Sales.ProductAvailabilityDataHistory", b =>
                {
                    b.Navigation("ProductPlacementDataHistory");
                });

            modelBuilder.Entity("GBA.Domain.Entities.Sales.StockStateStorage", b =>
                {
                    b.Navigation("ProductAvailabilityDataHistory");
                });
#pragma warning restore 612, 618
        }
    }
}
